### PR TITLE
Draft 25

### PR DESCRIPTION
**Pull request by ghedo**
This adds support for draft-25, while more or less keeping support for previous drafts.

Note that Retry is only supported with the latest draft (this was actually the case before as well, so :man_shrugging:).

### CODE REVIEW

**Comment by junhochoi** [comment]
Do we still need to support h3-23 as well?

**Comment by ghedo** [comment]
Added the idle_timeout changes as well. Also, apparently the fuzzers are not happy, so need to look into that.

**Comment by ghedo** [comment]
> Do we still need to support h3-23?

That's what Firefox stable supports, and if we keep draft-24 we don't really need to do anything to keep draft-23 as well.

**Comment by LPardue** [comment]
FWIW the change for `idle_timeout` also affects tools/http3_test/src/runner.rs and the `nginx-1.16.patch`

**Comment by ghedo** [comment]
I patched the NGINX patch, and also update the NGINX alt-svc example configration.

**Comment by ghedo** [comment]
And updated http3_test.

**Comment by ghedo** [comment]
Aaaand fixed the panic found by the fuzzers.

**Comment by LPardue** [comment]
:shipit:

**Pull request merged**
