### PR TITLE
pick lowest between idle and loss detection timers

### PR DESCRIPTION
**Pull request by ghedo**
Currently if idle timer is lower than loss timer, but loss timer is not
None, we will pick the loss timer over the idle one, so we might end up
never timing out the connection if there are outstanding packets that
have not been acknowledged.

### CODE REVIEW

**Comment by ghedo** [comment]
Oh wait, this doesn't work actually.

**Comment by ghedo** [comment]
Correction, it does work, but causes a bunch of spurious timeouts when draining timer is set. Updated it with fix.

**Comment by junhochoi** [comment]
> Currently if idle timer is lower than loss timer, but loss timer is not None, 

Can you describe what scenario it is? My understanding is that idle timeout is always bigger than PTO. ("10.2.  Idle Timeout" of -transport) and if there is unacked data we should continue with PTO  first.

**Comment by ghedo** [comment]
@junhochoi the PTO timer has a backoff mechanism (`timeout * (2 ^ pto_count)`) in case of repeated loss, so the idea here is that if `pto_count` is big enough, then the PTO timer will exceed idle timer.

Indeed the spec says:

>  When a PTO timer expires, the PTO period MUST be set to twice its current value. This exponential reduction in the sender’s rate is important because the PTOs might be caused by loss of packets or acknowledgements due to severe congestion. **The life of a connection that is experiencing consecutive PTOs is limited by the endpoint’s idle timeout**.

That last sentence is what appears to not be working correctly here. Though we are actually still testing whether this works as intended so I added the `hold` label back.

**Comment by junhochoi** [comment]
Also note that (-transport 10.2) it looks updated since draft 19:

> If the idle timeout is enabled, a connection is silently closed and the state is discarded when it remains idle for longer than both the advertised idle timeout (see Section 18.2) and three times the
   current Probe Timeout (PTO).
https://github.com/quicwg/base-drafts/commit/6f09658c18cfeca0df0c4b1fc435cceaf550b7e8

So idle timeout will be `max (<idle timeout advertised>, 3 * current_pto_timeout)`

And it seems like we restart idle timer only when sending packet, not when receiving packet. but this can be a separate issue.

**Comment by ghedo** [comment]
We restart the idle timer when receiving packets as well https://github.com/cloudflare/quiche/blob/master/src/lib.rs#L1363

**Pull request merged**
