### PR TITLE
README: update mention of test server

### PR DESCRIPTION
**Pull request by ghedo**
cloudflare-quic.com is more official.

### CODE REVIEW

**Comment by lohith-bellad** [comment]
I guess better to change in the command-line apps section as well to `cloudflare-quic.com`

**Comment by ghedo** [comment]
@lohith-bellad yes, good point. I updated the example command now.

**Comment by ghedo** [comment]
The clippy warnings are fixed in https://github.com/cloudflare/quiche/pull/800.

**Comment by ghedo** [comment]
Rebased with the fixes from the other PR.

**Review by lohith-bellad — APPROVED** [review]
LGTM

**Pull request merged**
