### PR TITLE
build: add soname to libquiche.so in android build

### PR DESCRIPTION
**Pull request by junhochoi**
Suggested by #598. Probably beneficial for other platform
build but currently only for android build.

### CODE REVIEW

**Comment by lu-zero** [comment]
Different os have different requirements for the soname.

https://crates.io/crates/cdylib-link-lines might help, a PRs to add android is welcome.

**Comment by junhochoi** [comment]
> Different os have different requirements for the soname.
> 
> https://crates.io/crates/cdylib-link-lines might help, a PRs to add android is welcome.

Sounds good but it will add one more dependency. @ghedo how do you think?

**Comment by ghedo** [comment]
I think we can gate it behind an optional feature at build time, so the people interested can enable it. This would probably also fix https://github.com/cloudflare/quiche/issues/165 btw, if we don't limit it to just Android.

**Comment by lu-zero** [comment]
I suggested already to use `cargo-c` to avoid adding dependencies. But currently Android is not among the targets supported so some patches would be welcomed :)

**Comment by junhochoi** [comment]
Closing in favor of #1769

**Pull request closed without merging**
