### PR TITLE
CI: macOS M1 architecture

### PR DESCRIPTION
**Pull request by junhochoi**
Add `macos-latest-xlarge` target for building on Apple Sillicon macOS.

### CODE REVIEW

**Comment by junhochoi** [comment]
This new job failed with:
```
The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.
```
Probably because this m1 runner is paid one.

**Comment by junhochoi** [comment]
> This new job failed with:
> 
> ```
> The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.
> ```
> 
> Probably because this m1 runner is paid one.

It works on my account : https://github.com/junhochoi/quiche/actions/runs/6819661072/job/18547366616
I had to increase my Action limit (default 0 -> some amount) to run this.

And it's very fast!. Total time for macos-latest (Intel): 1m14s vs macos-latest-xlarge (m1): 3m41s (3x faster)
(Yes faster probably because this is xlarge instance)

I'll let the maintainers to merge this or not.

**Comment by glandium** [comment]
You can use macos-14 now.

**Comment by junhochoi** [comment]
> You can use macos-14 now.

Thanks! I updated the PR to use macos-14. The build is green now.

Perf looks great.
- `macos-latest` (x86_64): 5m3s
- `macos-14` (aarch64): 1m42s

**Review by rushilmehra — APPROVED** [review]

**Comment by junhochoi** [comment]
rebased.

**Comment by ghedo** [comment]
Sorry for the delay, this merged now, thanks @junhochoi!

**Pull request merged**
