### PR TITLE
Downgrade epoch to Initial if remote peer can't decrypt yet

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We should downgrade the epoch to Initial if the remote peer cant decrypt yet, failing to do so might cause the remote peer to drop the frames on the floor and trying to resend.

Modifications:

Check if we need to downgrade to Intial and if so do it.

Result:

Remote peer can always handle frame

### CODE REVIEW

**Comment by normanmaurer** [comment]
Will work on a unit test

**Comment by normanmaurer** [comment]
@ghedo this has a unit test now which failed before the change. I used the `#[cfg(test)]` macro to expose stuff only for testing. If you have an other preference on how to do this let me know.

**Review by ghedo — APPROVED** [review]
Change lgtm overall, but I refactored the code slightly.

**Comment by ghedo** [comment]
Merged, thanks @normanmaurer!

**Pull request merged**
