### PR TITLE
cubic: remove direct dependency on libm crate

### PR DESCRIPTION
**Pull request by ghedo**

### CODE REVIEW

**Comment by junhochoi** [comment]
This means we will need `-lm` for C applications now on?

**Comment by ghedo** [comment]
@junhochoi we already do, don't we?
https://github.com/cloudflare/quiche/blob/master/examples/Makefile#L20
https://github.com/cloudflare/quiche/blob/master/extras/nginx/nginx-1.16.patch#L121

**Comment by junhochoi** [comment]
Right but it's a workaround (#979 and #1042) for a recent linux build and actually macos is ok without `-lm`. This looks like rust + linux platform issue (hopefully fixed in later version?)

Or I'm ok if we remove libm this time and `-lm` by default for C apps -- then we need to update docs too.

**Comment by ghedo** [comment]
Ok, thanks. It seems better to just keep things as they are now.

**Pull request closed without merging**
